version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 test.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
